version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "gitleaks/gitleaks-action"
        versions: [">= 3.0.0"]
