name: Release and Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to push tags/create releases

jobs:
  release:
    uses: borch-ai/.github/.github/workflows/release-basic.yml@main
    secrets: inherit
